
services:

  hh_grabber:
    image: hh_grabber:0.3
    build: hh_grabber
    ports:
      - "8001:8000"

  zarplata_grabber:
    image: zarplata_grabber:0.1
    build: zarplata_grabber
    ports:
      - "8002:8000"

#  scheduler:
#    image: scheduler:0.1
#    build: scheduler

  assistant_ui:
    image: assistant_ui:0.1
    build: ui
    ports:
      - "8501:8501"

  description_analyzer:
    image: description_analyser:0.1
    build: description_analyzer
    ports:
      - "8003:8000"


  grafana:
    image: grafana/grafana-enterprise:latest
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: public
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6380:6379"
    #volumes:
      #- redis_data:/data

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secure_password
    #volumes:
      #- rabbitmq_data:/var/lib/rabbitmq
      #- rabbitmq_log:/var/log/rabbitmq
 
volumes:
  grafana-data:
  postgres_data:
#  redis_data:
#  rabbitmq_data:
#  rabbitmq_log:

