
services:

  hh_grabber:
    image: hh_grabber:0.3
    build: hh_grabber
    ports:
      - "8000:8000"

  scheduler:
    image: scheduler:0.1
    build: scheduler

  assistant_ui:
    image: assistant_ui:0.1
    build: ui
    ports:
      - "8501:8501"

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: public
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  grafana-data:
  postgres_data:

