{
 "title": "hh.ru monitor",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "loaded vacancies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "select date(dt) date, count(*) vac_count\nfrom hh_ds \ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Созданные и закрытые вакансии",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT start_dt::date, COUNT(vac_id) \"Создано вакансий\" \nFROM vacancies_start_end_date \nGROUP BY start_dt \nLIMIT 50\n"
    },
    {
     "dataset": "public",
     "rawSql": "SELECT\n  end_dt::date,\n  COUNT(vac_id) \"Закрыто вакансий\"\nFROM\n  vacancies_start_end_date\nGROUP BY\n  1\nLIMIT\n  50"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "with cte1 as (\n  select distinct dt\n  from hh_ds order by 1),\ncte2 as (\n  SELECT hh_ds.dt, COUNT(*) AS \"error count\" \n  FROM hh_ds \n  left join vacancy_descriptions vd on hh_ds.vac_id = vd.vac_id\n  WHERE vd.vac_id IS NULL \n  GROUP BY dt \n)\nselect cte1.*,coalesce(cte2.\"error count\",0)\nfrom cte1\nleft join cte2 on cte1.dt = cte2.dt\n\n"
    }
   ]
  }
 ]
}