{
 "title": "hh.ru analysis",
 "description": "654",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "expirience",
    "label": "Опыт",
    "query": {
     "query": "SELECT distinct expirience FROM hh_ds LIMIT 50 "
    }
   },
   {
    "name": "company",
    "label": "Компании",
    "query": {
     "query": "SELECT distinct company FROM hh_ds\norder by 1"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Анализ рынка",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Топ 10 компаний по количеству вакансий",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 30 },
     "targets": [
      {
       "dataset": "public",
       "rawSql": "SELECT company,COUNT(*) as cnt \nFROM hh_ds_last_values \nwhere company in ($company)\n  and expirience in ($expirience) \nGROUP BY 1 \norder by cnt desc LIMIT 10 "
      },
      { "dataset": "public" }
     ]
    },
    {
     "title": "Формат работы",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "dataset": "public",
       "rawSql": "select coalesce(substring(vd.vac_work_format from 15),'Не указано') \"Формат работы\",count(*)\n from hh_ds_last_values hdlv \n join vacancy_descriptions vd  on vd.vac_id = hdlv.vac_id \n where hdlv.company in ($company)\n and hdlv.expirience in ($expirience) \n group by 1\n order by 2 desc"
      }
     ]
    },
    {
     "title": "Распределение вакансий по опыту",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 12, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "public",
       "rawSql": "SELECT expirience, COUNT(*) cnt\nFROM hh_ds_last_values \nwhere company in ($company)\n  and expirience in ($expirience) \nGROUP BY 1 \norder by 2 desc"
      }
     ]
    },
    {
     "title": "Распределение зарплат",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "dataset": "public",
       "rawSql": " with cte1 as (\n\tselect money, regexp_replace(replace(hdlv.money,'000',''), '(\\d+)\\s+(\\d+)','\\1\\2','g') money2\n\tfrom hh_ds_last_values hdlv \n\twhere hdlv.money like '%₽%'\n\tand company in ($company)\n  and expirience in ($expirience) \n\n\t--and hdlv.money not like '%–%'\n),\ncte2 as (\nselect money2, regexp_match(money2,'\\d+')::int[] money_arr \nfrom cte1\n)\nselect money_arr[1] \"зарплата\"\nfrom cte2"
      }
     ]
    }
   ]
  },
  {
   "title": "Skills analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 20 skills",
     "type": "barchart",
     "gridPos": { "h": 14, "w": 10, "x": 0, "y": 2 },
     "targets": [
      {
       "dataset": "public",
       "rawSql": "select skill, count(*)\nFROM last_vacancies_with_skills \nwhere company in ($company)\n  and expirience in ($expirience)\ngroup by 1\norder by 2 desc\nlimit 20"
      }
     ]
    }
   ]
  },
  {
   "title": "Работа с вакансиями",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Отклики/Отказы",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 39 },
     "targets": [
      {
       "dataset": "public",
       "rawSql": "select dt, count(distinct vac_id) \"Отказы\"\nfrom hh_ds\nwhere status = 'Вам отказали' \nGROUP BY 1"
      },
      {
       "dataset": "public",
       "rawSql": "select dt, count(*) \"Отклики\"\nfrom hh_ds\nwhere status = 'Вы откликнулись' \nGROUP BY 1"
      }
     ]
    },
    {
     "title": "Статусы вакансий",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 39 },
     "targets": [
      {
       "dataset": "public",
       "rawSql": "select status, count(distinct vac_id) \"Количество\"\nfrom hh_ds_last_values GROUP BY 1"
      }
     ]
    }
   ]
  }
 ]
}